apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort # Using NodePort so we can easily access it on localhost
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
